/**
 *  Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 *  By starting with 1 and 2, the first 10 terms will be:
 *    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

'use strict'

function FibGenerator(){
	let sum = 2; // corrected for the first even number, 2, not added to the sum during iteration
	let fibArray = [1,2];
    for (let i=2; fibArray[i-1] < 4e+6; i++){
        fibArray.push(fibArray[i - 2] + fibArray[i - 1]);
        if (fibArray[i]%2 == 0){
        	sum += fibArray[i];
        }
    }
    console.log("The sum of all even Fibonacci elements up to the element whose value does not exceed 4e+6 is " + sum +".");  
};

FibGenerator();